### ISSUE TITLE
作者好

### ISSUE THREAD

**Issue by xiaopohou** [ren8179/Qf.Core#2]
you~you~you ，我的QF哥，感谢你的框架，看着很规范，也不知道你这个是否可用于改造生产，同时不知道是否还继续更新，如果有可能，我们是否可以加一个联系方式，微信

**Comment by ren8179** [comment]
欢迎使用,项目会持续更新的.有问题可以发我的邮箱:ren8179@126.com

**Comment by xiaopohou** [comment]
好的 哥哥！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"非空"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午2:36
收件人:&nbsp;"ren8179/Qf.Core"<Qf.Core@noreply.github.com&gt;;
抄送:&nbsp;"└Monkey丶"<393331943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ren8179/Qf.Core] 作者好 (#2)





 
欢迎使用,项目会持续更新的.有问题可以发我的邮箱:ren8179@126.com

**Comment by xiaopohou** [comment]
哥好，请问您这个项目我现在是否可以投入生产去使用嘞？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"非空"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午2:36
收件人:&nbsp;"ren8179/Qf.Core"<Qf.Core@noreply.github.com&gt;;
抄送:&nbsp;"└Monkey丶"<393331943@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ren8179/Qf.Core] 作者好 (#2)





 
欢迎使用,项目会持续更新的.有问题可以发我的邮箱:ren8179@126.com

**Comment by ren8179** [comment]
建议你熟悉代码后再去使用
